# Generated by Django 4.1 on 2022-09-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='student',
            name='owner',
        ),
    ]
